import { UserRole } from '../types/user';

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  admin: ['*'],
  doctor: [
    'patients:read',
    'patients:write',
    'appointments:read',
    'appointments:write',
    'medical-records:read',
    'medical-records:write',
    'prescriptions:read',
    'prescriptions:write',
    'lab-requests:read',
    'lab-requests:write',
    'radiology-requests:read',
    'radiology-requests:write',
    'chat:read',
    'chat:write',
    'video-consultation:read',
    'video-consultation:write',
  ],
  nurse: [
    'patients:read',
    'vital-signs:read',
    'vital-signs:write',
    'medication:read',
    'medication:write',
    'nursing-notes:read',
    'nursing-notes:write',
    'appointments:read',
  ],
  receptionist: [
    'patients:read',
    'patients:write',
    'appointments:read',
    'appointments:write',
    'queue:read',
    'queue:write',
  ],
  pharmacist: [
    'medicines:read',
    'medicines:write',
    'prescriptions:read',
    'prescriptions:write',
    'inventory:read',
    'inventory:write',
    'sales:read',
    'sales:write',
  ],
  laboratory: [
    'lab-tests:read',
    'lab-tests:write',
    'lab-results:read',
    'lab-results:write',
    'sample-collection:read',
    'sample-collection:write',
  ],
  radiologist: [
    'radiology:read',
    'radiology:write',
    'radiology-reports:read',
    'radiology-reports:write',
  ],
  accountant: [
    'invoices:read',
    'invoices:write',
    'payments:read',
    'payments:write',
    'refunds:read',
    'refunds:write',
    'reports:read',
  ],
  ambulance_driver: [
    'emergencies:read',
    'emergencies:write',
    'ambulance:read',
    'ambulance:write',
    'location:read',
    'location:write',
  ],
  patient: [
    'profile:read',
    'profile:write',
    'appointments:read',
    'appointments:write',
    'medical-records:read',
    'prescriptions:read',
    'lab-results:read',
    'radiology:read',
    'payments:read',
    'payments:write',
    'chat:read',
    'chat:write',
    'video-consultation:read',
    'video-consultation:write',
  ],
};

export const ROLE_DASHBOARD_ROUTES: Record<UserRole, string> = {
  admin: '/dashboard/admin',
  doctor: '/dashboard/doctor',
  nurse: '/dashboard/nurse',
  receptionist: '/dashboard/receptionist',
  pharmacist: '/dashboard/pharmacy',
  laboratory: '/dashboard/laboratory',
  radiologist: '/dashboard/radiology',
  accountant: '/dashboard/accountant',
  ambulance_driver: '/dashboard/ambulance',
  patient: '/dashboard/patient',
};

export const ROLE_LABELS: Record<UserRole, string> = {
  admin: 'Administrator',
  doctor: 'Doctor',
  nurse: 'Nurse',
  receptionist: 'Receptionist',
  pharmacist: 'Pharmacist',
  laboratory: 'Laboratory Staff',
  radiologist: 'Radiologist',
  accountant: 'Accountant',
  ambulance_driver: 'Ambulance Driver',
  patient: 'Patient',
};