import { UserRole } from '../types/user';

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  super_admin: ['*'],
  admin: ['*'],
  doctor: [
    'patients:read',
    'patients:write',
    'appointments:read',
    'appointments:write',
    'medical-records:read',
    'medical-records:write',
    'prescriptions:read',
    'prescriptions:write',
    'lab-requests:read',
    'lab-requests:write',
    'radiology-requests:read',
    'radiology-requests:write',
    'chat:read',
    'chat:write',
    'video-consultation:read',
    'video-consultation:write',
    'admissions:read',
    'admissions:write',
    'discharges:read',
    'discharges:write',
  ],
  nurse: [
    'patients:read',
    'vital-signs:read',
    'vital-signs:write',
    'medication:read',
    'medication:write',
    'nursing-notes:read',
    'nursing-notes:write',
    'appointments:read',
    'admissions:read',
    'admissions:write',
    'wards:read',
    'beds:read',
  ],
  receptionist: [
    'patients:read',
    'patients:write',
    'appointments:read',
    'appointments:write',
    'queue:read',
    'queue:write',
    'admissions:read',
    'billing:read',
  ],
  pharmacist: [
    'medicines:read',
    'medicines:write',
    'prescriptions:read',
    'prescriptions:write',
    'inventory:read',
    'inventory:write',
    'sales:read',
    'sales:write',
    'pharmacy:read',
    'pharmacy:write',
  ],
  lab_technician: [
    'lab-tests:read',
    'lab-tests:write',
    'lab-results:read',
    'lab-results:write',
    'sample-collection:read',
    'sample-collection:write',
    'laboratory:read',
  ],
  radiologist: [
    'radiology:read',
    'radiology:write',
    'radiology-reports:read',
    'radiology-reports:write',
  ],
  accountant: [
    'invoices:read',
    'invoices:write',
    'payments:read',
    'payments:write',
    'refunds:read',
    'refunds:write',
    'reports:read',
    'billing:read',
    'billing:write',
    'finance:read',
    'finance:write',
  ],
  hr: [
    'staff:read',
    'staff:write',
    'attendance:read',
    'attendance:write',
    'leave:read',
    'leave:write',
    'payroll:read',
    'payroll:write',
    'hr:read',
    'hr:write',
  ],
  ambulance_driver: [
    'emergencies:read',
    'emergencies:write',
    'ambulance:read',
    'ambulance:write',
    'location:read',
    'location:write',
  ],
  patient: [
    'profile:read',
    'profile:write',
    'appointments:read',
    'appointments:write',
    'medical-records:read',
    'prescriptions:read',
    'lab-results:read',
    'radiology:read',
    'payments:read',
    'payments:write',
    'chat:read',
    'chat:write',
    'video-consultation:read',
    'video-consultation:write',
  ],
};

export const ROLE_DASHBOARD_ROUTES: Record<UserRole, string> = {
  super_admin: '/dashboard/admin',
  admin: '/dashboard/admin',
  doctor: '/dashboard/doctor',
  nurse: '/dashboard/nurse',
  receptionist: '/dashboard/receptionist',
  pharmacist: '/dashboard/pharmacy',
  lab_technician: '/dashboard/laboratory',
  radiologist: '/dashboard/radiology',
  accountant: '/dashboard/accountant',
  hr: '/dashboard/hr',
  ambulance_driver: '/dashboard/ambulance',
  patient: '/dashboard/patient',
};

export const ROLE_LABELS: Record<UserRole, string> = {
  super_admin: 'Super Administrator',
  admin: 'Administrator',
  doctor: 'Doctor',
  nurse: 'Nurse',
  receptionist: 'Receptionist',
  pharmacist: 'Pharmacist',
  lab_technician: 'Laboratory Staff',
  radiologist: 'Radiologist',
  accountant: 'Accountant',
  hr: 'HR Personnel',
  ambulance_driver: 'Ambulance Driver',
  patient: 'Patient',
};
